### ISSUE TITLE
Linea 192 debería ser "self._header = nuevo_nodo" no "self._header.next = nuevo_nodo"

### ISSUE THREAD

**Issue by FerreyraDamian** [nachonovello1984/python_ed_fcad_uner#1]
https://github.com/nachonovello1984/python_ed_fcad_uner/blob/main/data_structures/linear/lists/linked_list.py

Si la lista está vacía debería reemplazar el primer nodo de valores None por los que deseamos ingresar en lugar de agregar otro nodo y no sobrescribirlo

Con .next:
![image](https://github.com/user-attachments/assets/149b98d2-a4d2-4eb3-937e-aa3878971b74)
Sin .next:
![image](https://github.com/user-attachments/assets/d421de46-ca11-4570-b11e-4943441a4474)

```Python
from linked_list_ext import LinkedList

# Prueba init
Sample = LinkedList()
print(Sample)

# Prueba push
for i in range(10):
    Sample.append(i)
print(Sample)
print(Sample._header.element)
#agrega un elemento a una lista enlazada
Sample.add_first(10)
print(Sample)

Sample.__reversed__()
print(Sample)
#agrega una lista de elemento a una lista enlazada
lista=["a","b","c","d"]
Sample.__iadd__(lista)
print(Sample)
```

**Comment by nachonovello1984** [comment]
Hola Damián. Es correcto el planteo de la línea 192. Aplicamos ese esquema para que sean más fáciles las implementaciones de los métodos __iter__ y __delitem__. Esta forma de trabajo es la misma que aplica el libro Data Structures & Algorithms in Python de Goodrich y Tamassia en el Capítulo 7: Linked Lists.  Podés ver un ejemplo de una implementación de una lista doblemente enlazada que inicia en la página 270 y cuya implementación está en la página 274.

**Comment by nachonovello1984** [comment]
Hola Damián. Es correcto el planteo de la línea 192. Aplicamos ese esquema para que sean más fáciles las implementaciones de los métodos iter y delitem. Esta forma de trabajo es la misma que aplica el libro Data Structures & Algorithms in Python de Goodrich y Tamassia en el Capítulo 7: Linked Lists. Podés ver un ejemplo de una implementación de una lista doblemente enlazada que inicia en la página 270 y cuya implementación está en la página 274.

**Comment by FerreyraDamian** [comment]
Gracias, ya entendí la explicación del libro con header y trailer y el por qué. En la 271 lo explica perfectamente. Modificamos nuestro código para que funcione y agregamos el trailer entonces
